# Generated by Django 4.1.1 on 2022-10-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rota',
            name='hora_chegada_prevista',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='rota',
            name='hora_partida_prevista',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='voo',
            name='hora_chegada',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='voo',
            name='hora_partida',
            field=models.TimeField(),
        ),
    ]
