# Generated by Django 4.1.2 on 2022-10-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0003_voo_rota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voo',
            name='hora_chegada',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='voo',
            name='hora_partida',
            field=models.TimeField(null=True),
        ),
    ]
