# Generated by Django 4.1.2 on 2022-11-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0005_alter_voo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voo',
            name='status',
            field=models.CharField(choices=[('em', 'embarcando'), ('ca', 'cancelado'), ('pr', 'programado'), ('ta', 'taxiando'), ('pt', 'pronto'), ('ao', 'autorizado'), ('vo', 'em_voo'), ('at', 'aterrisado')], max_length=2, null=True),
        ),
    ]
